/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

USE sensors;

DROP TABLE IF EXISTS valuess;
DROP TABLE IF EXISTS sensor;

CREATE TABLE IF NOT EXISTS sensor (
    sensorId INT NOT NULL AUTO_INCREMENT,
    customId VARCHAR(10) NOT NULL,
    name VARCHAR(100) DEFAULT NULL,
    archived TINYINT DEFAULT 0,
    PRIMARY KEY (sensorId)
);

CREATE TABLE IF NOT EXISTS valuess (
    logId INT NOT NULL AUTO_INCREMENT,
    sensorId INT,
    dateAndTime TIMESTAMP,
    temperature DECIMAL(4,2),
    lightcondition DECIMAL(5,2),
    archived TINYINT DEFAULT 0,

    PRIMARY KEY (logId),
    FOREIGN KEY (sensorId) REFERENCES sensor (sensorId) ON DELETE CASCADE
);

ALTER TABLE valuess AUTO_INCREMENT = 1;

SELECT * FROM sensor;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
